// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : CrossValidation::BDTG
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.36/04       [402436]
Creator        : pengshaogang
Date           : Sun Mar 15 21:37:16 2026
Host           : Darwin sequoiax.internal.macports.net 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:17 PDT 2025; root:xnu-11417.140.69~1/RELEASE_X86_64 x86_64
Dir            : /Users/pengshaogang/Documents/analysis/bphy25/B0Ks/after_PV_constr/aod_fidu_cor/mix3
Training events: 40086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
EncapsulatedMethodName: "BDTG" []
EncapsulatedMethodTypeName: "BDT" []
NumFolds: "5" [Number of folds to generate]
OutputEnsembling: "None" [Combines output from contained methods. If None, no combination is performed. (default None)]
SplitExpr: "int(fabs([event]))%int([NumFolds])" [The expression used to assign events to folds]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
ld_Lxy                        ld_Lxy                        ld_Lxy                        L_{xy}(K_{S})                 mm                                'F'    [3.00342488289,746.090332031]
jx_Lxy                        jx_Lxy                        jx_Lxy                        L_{xy}(B^{0})                 mm                                'F'    [0.200084775686,77.7826538086]
tq_rf_ratio                   tq_rf_ratio                   tq_rf_ratio                   p_{T}^{B^{0}K_{S}}/#Sigmap_{T}^{PV}                                  'F'    [0.200128704309,0.992060780525]
tq_rf_fitChi2NDF              tq_rf_fitChi2NDF              tq_rf_fitChi2NDF              #chi^{2}/N                                                      'F'    [0.0708782970905,1.79996430874]
ld_rf_pt                      ld_rf_pt                      ld_rf_pt                      p_{T}(K_{S})                  MeV                               'F'    [970.146911621,45881.3554688]
x_rf_pt                       x_rf_pt                       x_rf_pt                       p_{T}(K^{*0})                 MeV                               'F'    [1502.17297363,185025.421875]
NSpec 1
event                         event                         event                         I                                                               'F'    [4,99988]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "ld_Lxy", "jx_Lxy", "tq_rf_ratio", "tq_rf_fitChi2NDF", "ld_rf_pt", "x_rf_pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
